// DUID to Fuel Type Mapping for AEMO SCADA Data
// Based on OpenNEM generator database
// This mapping is used to categorize generation by fuel type

export interface GeneratorInfo {
  fuel_type: string;
  station_name: string;
  capacity_mw: number;
  region: string;
}

// Comprehensive DUID mapping based on OpenNEM data
export const DUID_FUEL_MAP: Record<string, GeneratorInfo> = {
  // Coal - Black
  'BW01': { fuel_type: 'black_coal', station_name: 'Bayswater', capacity_mw: 660, region: 'NSW1' },
  'BW02': { fuel_type: 'black_coal', station_name: 'Bayswater', capacity_mw: 660, region: 'NSW1' },
  'BW03': { fuel_type: 'black_coal', station_name: 'Bayswater', capacity_mw: 660, region: 'NSW1' },
  'BW04': { fuel_type: 'black_coal', station_name: 'Bayswater', capacity_mw: 660, region: 'NSW1' },
  'ER01': { fuel_type: 'black_coal', station_name: 'Eraring', capacity_mw: 720, region: 'NSW1' },
  'ER02': { fuel_type: 'black_coal', station_name: 'Eraring', capacity_mw: 720, region: 'NSW1' },
  'ER03': { fuel_type: 'black_coal', station_name: 'Eraring', capacity_mw: 720, region: 'NSW1' },
  'ER04': { fuel_type: 'black_coal', station_name: 'Eraring', capacity_mw: 720, region: 'NSW1' },
  'VP5': { fuel_type: 'black_coal', station_name: 'Vales Point', capacity_mw: 660, region: 'NSW1' },
  'VP6': { fuel_type: 'black_coal', station_name: 'Vales Point', capacity_mw: 660, region: 'NSW1' },
  'MP1': { fuel_type: 'black_coal', station_name: 'Mt Piper', capacity_mw: 700, region: 'NSW1' },
  'MP2': { fuel_type: 'black_coal', station_name: 'Mt Piper', capacity_mw: 730, region: 'NSW1' },
  'MPP_1': { fuel_type: 'black_coal', station_name: 'Mt Piper', capacity_mw: 700, region: 'NSW1' },
  'MPP_2': { fuel_type: 'black_coal', station_name: 'Mt Piper', capacity_mw: 730, region: 'NSW1' },
  'CALL_B_1': { fuel_type: 'black_coal', station_name: 'Callide B', capacity_mw: 350, region: 'QLD1' },
  'CALL_B_2': { fuel_type: 'black_coal', station_name: 'Callide B', capacity_mw: 350, region: 'QLD1' },
  'CPP_3': { fuel_type: 'black_coal', station_name: 'Callide C', capacity_mw: 420, region: 'QLD1' },
  'CPP_4': { fuel_type: 'black_coal', station_name: 'Callide C', capacity_mw: 420, region: 'QLD1' },
  'GSTONE1': { fuel_type: 'black_coal', station_name: 'Gladstone', capacity_mw: 280, region: 'QLD1' },
  'GSTONE2': { fuel_type: 'black_coal', station_name: 'Gladstone', capacity_mw: 280, region: 'QLD1' },
  'GSTONE3': { fuel_type: 'black_coal', station_name: 'Gladstone', capacity_mw: 280, region: 'QLD1' },
  'GSTONE4': { fuel_type: 'black_coal', station_name: 'Gladstone', capacity_mw: 280, region: 'QLD1' },
  'GSTONE5': { fuel_type: 'black_coal', station_name: 'Gladstone', capacity_mw: 280, region: 'QLD1' },
  'GSTONE6': { fuel_type: 'black_coal', station_name: 'Gladstone', capacity_mw: 280, region: 'QLD1' },
  'KPP_1': { fuel_type: 'black_coal', station_name: 'Kogan Creek', capacity_mw: 744, region: 'QLD1' },
  'STAN-1': { fuel_type: 'black_coal', station_name: 'Stanwell', capacity_mw: 365, region: 'QLD1' },
  'STAN-2': { fuel_type: 'black_coal', station_name: 'Stanwell', capacity_mw: 365, region: 'QLD1' },
  'STAN-3': { fuel_type: 'black_coal', station_name: 'Stanwell', capacity_mw: 365, region: 'QLD1' },
  'STAN-4': { fuel_type: 'black_coal', station_name: 'Stanwell', capacity_mw: 365, region: 'QLD1' },
  'TARONG#1': { fuel_type: 'black_coal', station_name: 'Tarong', capacity_mw: 350, region: 'QLD1' },
  'TARONG#2': { fuel_type: 'black_coal', station_name: 'Tarong', capacity_mw: 350, region: 'QLD1' },
  'TARONG#3': { fuel_type: 'black_coal', station_name: 'Tarong', capacity_mw: 350, region: 'QLD1' },
  'TARONG#4': { fuel_type: 'black_coal', station_name: 'Tarong', capacity_mw: 350, region: 'QLD1' },
  'TNPS1': { fuel_type: 'black_coal', station_name: 'Tarong North', capacity_mw: 443, region: 'QLD1' },
  'MILL1': { fuel_type: 'black_coal', station_name: 'Millmerran', capacity_mw: 426, region: 'QLD1' },
  'MILL2': { fuel_type: 'black_coal', station_name: 'Millmerran', capacity_mw: 426, region: 'QLD1' },
  
  // Coal - Brown
  'LYA1': { fuel_type: 'brown_coal', station_name: 'Loy Yang A', capacity_mw: 530, region: 'VIC1' },
  'LYA2': { fuel_type: 'brown_coal', station_name: 'Loy Yang A', capacity_mw: 560, region: 'VIC1' },
  'LYA3': { fuel_type: 'brown_coal', station_name: 'Loy Yang A', capacity_mw: 560, region: 'VIC1' },
  'LYA4': { fuel_type: 'brown_coal', station_name: 'Loy Yang A', capacity_mw: 560, region: 'VIC1' },
  'LOYYB1': { fuel_type: 'brown_coal', station_name: 'Loy Yang B', capacity_mw: 500, region: 'VIC1' },
  'LOYYB2': { fuel_type: 'brown_coal', station_name: 'Loy Yang B', capacity_mw: 500, region: 'VIC1' },
  'YWPS1': { fuel_type: 'brown_coal', station_name: 'Yallourn W', capacity_mw: 370, region: 'VIC1' },
  'YWPS2': { fuel_type: 'brown_coal', station_name: 'Yallourn W', capacity_mw: 370, region: 'VIC1' },
  'YWPS3': { fuel_type: 'brown_coal', station_name: 'Yallourn W', capacity_mw: 370, region: 'VIC1' },
  'YWPS4': { fuel_type: 'brown_coal', station_name: 'Yallourn W', capacity_mw: 370, region: 'VIC1' },
  
  // Gas - CCGT
  'TALWA1': { fuel_type: 'gas_ccgt', station_name: 'Tallawarra', capacity_mw: 440, region: 'NSW1' },
  'TALWA2': { fuel_type: 'gas_ccgt', station_name: 'Tallawarra B', capacity_mw: 320, region: 'NSW1' },
  'CSPVPS1': { fuel_type: 'gas_ccgt', station_name: 'Condamine', capacity_mw: 143, region: 'QLD1' },
  'SWAN_E': { fuel_type: 'gas_ccgt', station_name: 'Swanbank E', capacity_mw: 385, region: 'QLD1' },
  'DDPS1': { fuel_type: 'gas_ccgt', station_name: 'Darling Downs', capacity_mw: 644, region: 'QLD1' },
  'PPCCGT': { fuel_type: 'gas_ccgt', station_name: 'Pelican Point', capacity_mw: 478, region: 'SA1' },
  'OSB-AG': { fuel_type: 'gas_ccgt', station_name: 'Osborne', capacity_mw: 180, region: 'SA1' },
  'MORTLK11': { fuel_type: 'gas_ccgt', station_name: 'Mortlake', capacity_mw: 283, region: 'VIC1' },
  'MORTLK12': { fuel_type: 'gas_ccgt', station_name: 'Mortlake', capacity_mw: 283, region: 'VIC1' },
  'YARWUN_1': { fuel_type: 'gas_ccgt', station_name: 'Yarwun', capacity_mw: 154, region: 'QLD1' },
  'TVCC201': { fuel_type: 'gas_ccgt', station_name: 'Tamar Valley', capacity_mw: 209, region: 'TAS1' },
  'BARCALDN': { fuel_type: 'gas_ccgt', station_name: 'Barcaldine', capacity_mw: 37, region: 'QLD1' },
  'TOWNSVL': { fuel_type: 'gas_ccgt', station_name: 'Townsville', capacity_mw: 242, region: 'QLD1' },
  
  // Gas - OCGT
  'URANQ11': { fuel_type: 'gas_ocgt', station_name: 'Uranquinty', capacity_mw: 166, region: 'NSW1' },
  'URANQ12': { fuel_type: 'gas_ocgt', station_name: 'Uranquinty', capacity_mw: 166, region: 'NSW1' },
  'URANQ13': { fuel_type: 'gas_ocgt', station_name: 'Uranquinty', capacity_mw: 166, region: 'NSW1' },
  'URANQ14': { fuel_type: 'gas_ocgt', station_name: 'Uranquinty', capacity_mw: 166, region: 'NSW1' },
  'BRAEMAR1': { fuel_type: 'gas_ocgt', station_name: 'Braemar', capacity_mw: 168, region: 'QLD1' },
  'BRAEMAR2': { fuel_type: 'gas_ocgt', station_name: 'Braemar', capacity_mw: 168, region: 'QLD1' },
  'BRAEMAR3': { fuel_type: 'gas_ocgt', station_name: 'Braemar', capacity_mw: 168, region: 'QLD1' },
  'BRAEMAR5': { fuel_type: 'gas_ocgt', station_name: 'Braemar 2', capacity_mw: 173, region: 'QLD1' },
  'BRAEMAR6': { fuel_type: 'gas_ocgt', station_name: 'Braemar 2', capacity_mw: 173, region: 'QLD1' },
  'BRAEMAR7': { fuel_type: 'gas_ocgt', station_name: 'Braemar 2', capacity_mw: 173, region: 'QLD1' },
  'LADBROK1': { fuel_type: 'gas_ocgt', station_name: 'Ladbroke Grove', capacity_mw: 40, region: 'SA1' },
  'LADBROK2': { fuel_type: 'gas_ocgt', station_name: 'Ladbroke Grove', capacity_mw: 40, region: 'SA1' },
  'MINTARO': { fuel_type: 'gas_ocgt', station_name: 'Mintaro', capacity_mw: 115, region: 'SA1' },
  'QUARRY1': { fuel_type: 'gas_ocgt', station_name: 'Quarantine', capacity_mw: 115, region: 'SA1' },
  'QUARRY2': { fuel_type: 'gas_ocgt', station_name: 'Quarantine', capacity_mw: 114, region: 'SA1' },
  'DRYCGT1': { fuel_type: 'gas_ocgt', station_name: 'Dry Creek', capacity_mw: 52, region: 'SA1' },
  'DRYCGT2': { fuel_type: 'gas_ocgt', station_name: 'Dry Creek', capacity_mw: 52, region: 'SA1' },
  'DRYCGT3': { fuel_type: 'gas_ocgt', station_name: 'Dry Creek', capacity_mw: 52, region: 'SA1' },
  'HALLETTGT1': { fuel_type: 'gas_ocgt', station_name: 'Hallett', capacity_mw: 109, region: 'SA1' },
  'HALLETTGT2': { fuel_type: 'gas_ocgt', station_name: 'Hallett', capacity_mw: 108, region: 'SA1' },
  'JLB01': { fuel_type: 'gas_ocgt', station_name: 'Jeeralang B', capacity_mw: 114, region: 'VIC1' },
  'JLB02': { fuel_type: 'gas_ocgt', station_name: 'Jeeralang B', capacity_mw: 114, region: 'VIC1' },
  'JLA01': { fuel_type: 'gas_ocgt', station_name: 'Jeeralang A', capacity_mw: 102, region: 'VIC1' },
  'JLA02': { fuel_type: 'gas_ocgt', station_name: 'Jeeralang A', capacity_mw: 102, region: 'VIC1' },
  'ROMA_7': { fuel_type: 'gas_ocgt', station_name: 'Roma', capacity_mw: 40, region: 'QLD1' },
  'ROMA_8': { fuel_type: 'gas_ocgt', station_name: 'Roma', capacity_mw: 40, region: 'QLD1' },
  'OAKEY1': { fuel_type: 'gas_ocgt', station_name: 'Oakey', capacity_mw: 141, region: 'QLD1' },
  'OAKEY2': { fuel_type: 'gas_ocgt', station_name: 'Oakey', capacity_mw: 141, region: 'QLD1' },
  'COLONGRA': { fuel_type: 'gas_ocgt', station_name: 'Colongra', capacity_mw: 724, region: 'NSW1' },
  'BBTHREE1': { fuel_type: 'gas_ocgt', station_name: 'Bell Bay Three', capacity_mw: 55, region: 'TAS1' },
  'BBTHREE2': { fuel_type: 'gas_ocgt', station_name: 'Bell Bay Three', capacity_mw: 54, region: 'TAS1' },
  'BBTHREE3': { fuel_type: 'gas_ocgt', station_name: 'Bell Bay Three', capacity_mw: 54, region: 'TAS1' },
  
  // Gas - Steam
  'TORRENS1': { fuel_type: 'gas_steam', station_name: 'Torrens Island', capacity_mw: 200, region: 'SA1' },
  'TORRENS2': { fuel_type: 'gas_steam', station_name: 'Torrens Island', capacity_mw: 200, region: 'SA1' },
  'TORRENS3': { fuel_type: 'gas_steam', station_name: 'Torrens Island', capacity_mw: 200, region: 'SA1' },
  'TORRENS4': { fuel_type: 'gas_steam', station_name: 'Torrens Island', capacity_mw: 200, region: 'SA1' },
  'TORRB3': { fuel_type: 'gas_steam', station_name: 'Torrens Island', capacity_mw: 200, region: 'SA1' },
  'NPS1': { fuel_type: 'gas_steam', station_name: 'Newport', capacity_mw: 250, region: 'VIC1' },
  'NPS2': { fuel_type: 'gas_steam', station_name: 'Newport', capacity_mw: 250, region: 'VIC1' },
  
  // Hydro
  'TUMUT1': { fuel_type: 'hydro', station_name: 'Tumut', capacity_mw: 330, region: 'NSW1' },
  'TUMUT2': { fuel_type: 'hydro', station_name: 'Tumut', capacity_mw: 286, region: 'NSW1' },
  'TUMUT3': { fuel_type: 'hydro', station_name: 'Tumut 3', capacity_mw: 1500, region: 'NSW1' },
  'UPPTUMUT': { fuel_type: 'hydro', station_name: 'Upper Tumut', capacity_mw: 220, region: 'NSW1' },
  'MURRAY': { fuel_type: 'hydro', station_name: 'Murray', capacity_mw: 1500, region: 'VIC1' },
  'MURRAY1': { fuel_type: 'hydro', station_name: 'Murray 1', capacity_mw: 950, region: 'NSW1' },
  'MURRAY2': { fuel_type: 'hydro', station_name: 'Murray 2', capacity_mw: 550, region: 'NSW1' },
  'GUTHEGA': { fuel_type: 'hydro', station_name: 'Guthega', capacity_mw: 60, region: 'NSW1' },
  'BLOWERNG': { fuel_type: 'hydro', station_name: 'Blowering', capacity_mw: 80, region: 'NSW1' },
  'MACKAYS1': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 59, region: 'VIC1' },
  'MACKAYS2': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 59, region: 'VIC1' },
  'MACKAYS3': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 59, region: 'VIC1' },
  'MACKAYS4': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 59, region: 'VIC1' },
  'MACKAYS5': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 59, region: 'VIC1' },
  'MACKAYS6': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 59, region: 'VIC1' },
  'EILDON1': { fuel_type: 'hydro', station_name: 'Eildon', capacity_mw: 60, region: 'VIC1' },
  'EILDON2': { fuel_type: 'hydro', station_name: 'Eildon', capacity_mw: 60, region: 'VIC1' },
  'WKIEWA1': { fuel_type: 'hydro', station_name: 'West Kiewa', capacity_mw: 31, region: 'VIC1' },
  'WKIEWA2': { fuel_type: 'hydro', station_name: 'West Kiewa', capacity_mw: 31, region: 'VIC1' },
  'DARTM1': { fuel_type: 'hydro', station_name: 'Dartmouth', capacity_mw: 185, region: 'VIC1' },
  'KAREEYA1': { fuel_type: 'hydro', station_name: 'Kareeya', capacity_mw: 22, region: 'QLD1' },
  'KAREEYA2': { fuel_type: 'hydro', station_name: 'Kareeya', capacity_mw: 22, region: 'QLD1' },
  'KAREEYA3': { fuel_type: 'hydro', station_name: 'Kareeya', capacity_mw: 24, region: 'QLD1' },
  'KAREEYA4': { fuel_type: 'hydro', station_name: 'Kareeya', capacity_mw: 23, region: 'QLD1' },
  'BARRON-1': { fuel_type: 'hydro', station_name: 'Barron Gorge', capacity_mw: 30, region: 'QLD1' },
  'BARRON-2': { fuel_type: 'hydro', station_name: 'Barron Gorge', capacity_mw: 30, region: 'QLD1' },
  'GORDON': { fuel_type: 'hydro', station_name: 'Gordon', capacity_mw: 457, region: 'TAS1' },
  'POATINA': { fuel_type: 'hydro', station_name: 'Poatina', capacity_mw: 325, region: 'TAS1' },
  'REECE1': { fuel_type: 'hydro', station_name: 'Reece', capacity_mw: 116, region: 'TAS1' },
  'REECE2': { fuel_type: 'hydro', station_name: 'Reece', capacity_mw: 116, region: 'TAS1' },
  'TREVALLN': { fuel_type: 'hydro', station_name: 'Trevallyn', capacity_mw: 93, region: 'TAS1' },
  'JBUTTERS': { fuel_type: 'hydro', station_name: 'John Butters', capacity_mw: 144, region: 'TAS1' },
  'FISHER': { fuel_type: 'hydro', station_name: 'Fisher', capacity_mw: 43, region: 'TAS1' },
  'DEVILS_G': { fuel_type: 'hydro', station_name: 'Devils Gate', capacity_mw: 60, region: 'TAS1' },
  'CETHANA': { fuel_type: 'hydro', station_name: 'Cethana', capacity_mw: 85, region: 'TAS1' },
  'ROWALLAN': { fuel_type: 'hydro', station_name: 'Rowallan', capacity_mw: 11, region: 'TAS1' },
  'BASTYAN': { fuel_type: 'hydro', station_name: 'Bastyan', capacity_mw: 80, region: 'TAS1' },
  'MEADOWBK': { fuel_type: 'hydro', station_name: 'Meadowbank', capacity_mw: 40, region: 'TAS1' },
  'TARRALEA': { fuel_type: 'hydro', station_name: 'Tarraleah', capacity_mw: 90, region: 'TAS1' },
  'TUNGATIN': { fuel_type: 'hydro', station_name: 'Tungatinah', capacity_mw: 125, region: 'TAS1' },
  'BUTLERSG': { fuel_type: 'hydro', station_name: 'Butlers Gorge', capacity_mw: 14, region: 'TAS1' },
  'LAKEEECHO': { fuel_type: 'hydro', station_name: 'Lake Echo', capacity_mw: 32, region: 'TAS1' },
  'CATAGUNYA': { fuel_type: 'hydro', station_name: 'Catagunya', capacity_mw: 48, region: 'TAS1' },
  'LIAPOOTAH': { fuel_type: 'hydro', station_name: 'Liapootah', capacity_mw: 83, region: 'TAS1' },
  'WAYATINAH': { fuel_type: 'hydro', station_name: 'Wayatinah', capacity_mw: 43, region: 'TAS1' },
  'REPULSE': { fuel_type: 'hydro', station_name: 'Repulse', capacity_mw: 28, region: 'TAS1' },
  'CLUNY': { fuel_type: 'hydro', station_name: 'Cluny', capacity_mw: 19, region: 'TAS1' },
  'MACKINTOSH': { fuel_type: 'hydro', station_name: 'Mackintosh', capacity_mw: 80, region: 'TAS1' },
  'LEMONTHYME': { fuel_type: 'hydro', station_name: 'Lemonthyme', capacity_mw: 52, region: 'TAS1' },
  'WILMOT': { fuel_type: 'hydro', station_name: 'Wilmot', capacity_mw: 30, region: 'TAS1' },
  'TRIBUTE': { fuel_type: 'hydro', station_name: 'Tribute', capacity_mw: 108, region: 'TAS1' },
  'SHOAL1': { fuel_type: 'hydro', station_name: 'Shoalhaven', capacity_mw: 240, region: 'NSW1' },
  'CLOVER': { fuel_type: 'hydro', station_name: 'Clover', capacity_mw: 29, region: 'VIC1' },
  'RUBICON': { fuel_type: 'hydro', station_name: 'Rubicon', capacity_mw: 13, region: 'VIC1' },
  'W/HOE#1': { fuel_type: 'hydro', station_name: 'Wivenhoe', capacity_mw: 285, region: 'QLD1' },
  'W/HOE#2': { fuel_type: 'hydro', station_name: 'Wivenhoe', capacity_mw: 285, region: 'QLD1' },
  
  // Wind
  'ARWF1': { fuel_type: 'wind', station_name: 'Ararat', capacity_mw: 242, region: 'VIC1' },
  'BALDHWF1': { fuel_type: 'wind', station_name: 'Bald Hills', capacity_mw: 107, region: 'VIC1' },
  'BANGOWF1': { fuel_type: 'wind', station_name: 'Bango', capacity_mw: 122, region: 'NSW1' },
  'BANGOWF2': { fuel_type: 'wind', station_name: 'Bango', capacity_mw: 122, region: 'NSW1' },
  'BERYLWF1': { fuel_type: 'wind', station_name: 'Berrybank', capacity_mw: 180, region: 'VIC1' },
  'BOCORWF1': { fuel_type: 'wind', station_name: 'Boco Rock', capacity_mw: 113, region: 'NSW1' },
  'BODWF1': { fuel_type: 'wind', station_name: 'Bodangora', capacity_mw: 113, region: 'NSW1' },
  'BRYB1WF1': { fuel_type: 'wind', station_name: 'Berrybank', capacity_mw: 110, region: 'VIC1' },
  'BRYB2WF2': { fuel_type: 'wind', station_name: 'Berrybank', capacity_mw: 110, region: 'VIC1' },
  'BULGANA1': { fuel_type: 'wind', station_name: 'Bulgana', capacity_mw: 204, region: 'VIC1' },
  'CAPTL_WF': { fuel_type: 'wind', station_name: 'Capital', capacity_mw: 140, region: 'NSW1' },
  'CATHROCK': { fuel_type: 'wind', station_name: 'Cathedral Rocks', capacity_mw: 66, region: 'SA1' },
  'CHALLHWF': { fuel_type: 'wind', station_name: 'Challicum Hills', capacity_mw: 53, region: 'VIC1' },
  'CHEPSWF1': { fuel_type: 'wind', station_name: 'Chepstowe', capacity_mw: 6, region: 'VIC1' },
  'CHERTWF1': { fuel_type: 'wind', station_name: 'Cherry Tree', capacity_mw: 58, region: 'VIC1' },
  'CLEMGPWF': { fuel_type: 'wind', station_name: 'Clements Gap', capacity_mw: 57, region: 'SA1' },
  'COOPERWF': { fuel_type: 'wind', station_name: 'Coopers Gap', capacity_mw: 452, region: 'QLD1' },
  'CROOKWF2': { fuel_type: 'wind', station_name: 'Crookwell 2', capacity_mw: 96, region: 'NSW1' },
  'CROOKWF3': { fuel_type: 'wind', station_name: 'Crookwell 3', capacity_mw: 57, region: 'NSW1' },
  'CROWLWF1': { fuel_type: 'wind', station_name: 'Crowlands', capacity_mw: 80, region: 'VIC1' },
  'CRUDWF1': { fuel_type: 'wind', station_name: 'Crudine Ridge', capacity_mw: 141, region: 'NSW1' },
  'CULLRGWF': { fuel_type: 'wind', station_name: 'Cullerin Range', capacity_mw: 30, region: 'NSW1' },
  'DULWF1': { fuel_type: 'wind', station_name: 'Dulacca', capacity_mw: 180, region: 'QLD1' },
  'DUNDWF1': { fuel_type: 'wind', station_name: 'Dundonnell', capacity_mw: 335, region: 'VIC1' },
  'ELAINEWF': { fuel_type: 'wind', station_name: 'Elaine', capacity_mw: 84, region: 'VIC1' },
  'FLYRCWF1': { fuel_type: 'wind', station_name: 'Flyers Creek', capacity_mw: 145, region: 'NSW1' },
  'GANAWF1': { fuel_type: 'wind', station_name: 'Granville Harbour', capacity_mw: 110, region: 'TAS1' },
  'GERMCRK': { fuel_type: 'wind', station_name: 'German Creek', capacity_mw: 45, region: 'QLD1' },
  'GOLDWF01': { fuel_type: 'wind', station_name: 'Golden Plains East', capacity_mw: 756, region: 'VIC1' },
  'GOYDHSF1': { fuel_type: 'wind', station_name: 'Goyder South', capacity_mw: 413, region: 'SA1' },
  'GUNNING1': { fuel_type: 'wind', station_name: 'Gunning', capacity_mw: 47, region: 'NSW1' },
  'HALLWF1': { fuel_type: 'wind', station_name: 'Hallett 1', capacity_mw: 95, region: 'SA1' },
  'HALLWF2': { fuel_type: 'wind', station_name: 'Hallett 2', capacity_mw: 71, region: 'SA1' },
  'HAWKWF1': { fuel_type: 'wind', station_name: 'Hawkesdale', capacity_mw: 95, region: 'VIC1' },
  'HDWF1': { fuel_type: 'wind', station_name: 'Hornsdale', capacity_mw: 102, region: 'SA1' },
  'HDWF2': { fuel_type: 'wind', station_name: 'Hornsdale 2', capacity_mw: 102, region: 'SA1' },
  'HDWF3': { fuel_type: 'wind', station_name: 'Hornsdale 3', capacity_mw: 112, region: 'SA1' },
  'KIATAWF1': { fuel_type: 'wind', station_name: 'Kiata', capacity_mw: 31, region: 'VIC1' },
  'LKBONNY1': { fuel_type: 'wind', station_name: 'Lake Bonney', capacity_mw: 81, region: 'SA1' },
  'LKBONNY2': { fuel_type: 'wind', station_name: 'Lake Bonney 2', capacity_mw: 159, region: 'SA1' },
  'LKBONNY3': { fuel_type: 'wind', station_name: 'Lake Bonney 3', capacity_mw: 39, region: 'SA1' },
  'LGAPWF1': { fuel_type: 'wind', station_name: 'Lincoln Gap', capacity_mw: 212, region: 'SA1' },
  'MACARTH1': { fuel_type: 'wind', station_name: 'Macarthur', capacity_mw: 420, region: 'VIC1' },
  'MACKWF1': { fuel_type: 'wind', station_name: 'MacIntyre', capacity_mw: 923, region: 'QLD1' },
  'MLWF1': { fuel_type: 'wind', station_name: 'Mt Millar', capacity_mw: 70, region: 'SA1' },
  'MOORAWF1': { fuel_type: 'wind', station_name: 'Moorabool', capacity_mw: 312, region: 'VIC1' },
  'MORTLWF1': { fuel_type: 'wind', station_name: 'Mortlake South', capacity_mw: 158, region: 'VIC1' },
  'MTEMERWF': { fuel_type: 'wind', station_name: 'Mt Emerald', capacity_mw: 180, region: 'QLD1' },
  'MTGELWF1': { fuel_type: 'wind', station_name: 'Mt Gellibrand', capacity_mw: 138, region: 'VIC1' },
  'MTMILLAR': { fuel_type: 'wind', station_name: 'Mt Millar', capacity_mw: 70, region: 'SA1' },
  'MUSSELR1': { fuel_type: 'wind', station_name: 'Musselroe', capacity_mw: 168, region: 'TAS1' },
  'NBHWF1': { fuel_type: 'wind', station_name: 'North Brown Hill', capacity_mw: 132, region: 'SA1' },
  'OAKLAND1': { fuel_type: 'wind', station_name: 'Oaklands Hill', capacity_mw: 67, region: 'VIC1' },
  'PORTWF': { fuel_type: 'wind', station_name: 'Portland', capacity_mw: 148, region: 'VIC1' },
  'RYEPARK1': { fuel_type: 'wind', station_name: 'Rye Park', capacity_mw: 396, region: 'NSW1' },
  'RYANWF1': { fuel_type: 'wind', station_name: 'Ryan Corner', capacity_mw: 218, region: 'VIC1' },
  'SALTCRK1': { fuel_type: 'wind', station_name: 'Salt Creek', capacity_mw: 54, region: 'VIC1' },
  'SILVWF1': { fuel_type: 'wind', station_name: 'Silverton', capacity_mw: 198, region: 'NSW1' },
  'SAPPHWF1': { fuel_type: 'wind', station_name: 'Sapphire', capacity_mw: 270, region: 'NSW1' },
  'SNOWTWN1': { fuel_type: 'wind', station_name: 'Snowtown', capacity_mw: 99, region: 'SA1' },
  'SNOWNTH1': { fuel_type: 'wind', station_name: 'Snowtown North', capacity_mw: 144, region: 'SA1' },
  'SNOWSTH1': { fuel_type: 'wind', station_name: 'Snowtown South', capacity_mw: 126, region: 'SA1' },
  'STARHLWF': { fuel_type: 'wind', station_name: 'Starfish Hill', capacity_mw: 35, region: 'SA1' },
  'STOCKYD1': { fuel_type: 'wind', station_name: 'Stockyard Hill', capacity_mw: 531, region: 'VIC1' },
  'TALRGWF1': { fuel_type: 'wind', station_name: 'Taralga', capacity_mw: 107, region: 'NSW1' },
  'CTHLWF1': { fuel_type: 'wind', station_name: 'Cattle Hill', capacity_mw: 148, region: 'TAS1' },
  'TOORAWF1': { fuel_type: 'wind', station_name: 'Toora', capacity_mw: 21, region: 'VIC1' },
  'WAMBOWF1': { fuel_type: 'wind', station_name: 'Wambo', capacity_mw: 252, region: 'QLD1' },
  'WATERLWF': { fuel_type: 'wind', station_name: 'Waterloo', capacity_mw: 130, region: 'SA1' },
  'WATTLEPT': { fuel_type: 'wind', station_name: 'Wattle Point', capacity_mw: 91, region: 'SA1' },
  'WAUBRAWF': { fuel_type: 'wind', station_name: 'Waubra', capacity_mw: 192, region: 'VIC1' },
  'WHITERF1': { fuel_type: 'wind', station_name: 'White Rock', capacity_mw: 175, region: 'NSW1' },
  'WILLOGWF': { fuel_type: 'wind', station_name: 'Willogoleche', capacity_mw: 119, region: 'SA1' },
  'WNDHLWF1': { fuel_type: 'wind', station_name: 'Windy Hill', capacity_mw: 12, region: 'QLD1' },
  'WGWF1': { fuel_type: 'wind', station_name: 'Wonthaggi', capacity_mw: 12, region: 'VIC1' },
  'WOODLWN1': { fuel_type: 'wind', station_name: 'Woodlawn', capacity_mw: 48, region: 'NSW1' },
  'WOOLNTH1': { fuel_type: 'wind', station_name: 'Woolnorth', capacity_mw: 140, region: 'TAS1' },
  'YAMBUKWF': { fuel_type: 'wind', station_name: 'Yambuk', capacity_mw: 30, region: 'VIC1' },
  'YALNTH1': { fuel_type: 'wind', station_name: 'Yaloak South', capacity_mw: 29, region: 'VIC1' },
  'YENDONWF': { fuel_type: 'wind', station_name: 'Yendon', capacity_mw: 144, region: 'VIC1' },
  'YAWONGWF': { fuel_type: 'wind', station_name: 'Yawong', capacity_mw: 7, region: 'VIC1' },
  'DIAPURWF1': { fuel_type: 'wind', station_name: 'Diapur 2', capacity_mw: 8, region: 'VIC1' },
  'COLLWF1': { fuel_type: 'wind', station_name: 'Collector', capacity_mw: 226, region: 'NSW1' },
  'KABAN1': { fuel_type: 'wind', station_name: 'Kaban', capacity_mw: 156, region: 'QLD1' },
  'CODRNGWF': { fuel_type: 'wind', station_name: 'Codrington', capacity_mw: 18, region: 'VIC1' },
  'HEPBURNWF': { fuel_type: 'wind', station_name: 'Hepburn', capacity_mw: 4, region: 'VIC1' },
  'MORTNWF1': { fuel_type: 'wind', station_name: 'Mortons Lane', capacity_mw: 20, region: 'VIC1' },
  'CANUNDWF': { fuel_type: 'wind', station_name: 'Canunda', capacity_mw: 46, region: 'SA1' },
  'CLKEWF1': { fuel_type: 'wind', station_name: 'Clarke Creek', capacity_mw: 450, region: 'QLD1' },
  'COONOERWF': { fuel_type: 'wind', station_name: 'Coonoer Bridge', capacity_mw: 20, region: 'VIC1' },
  'MERCER01': { fuel_type: 'wind', station_name: 'Mt Mercer', capacity_mw: 131, region: 'VIC1' },
  'TIMBOWF1': { fuel_type: 'wind', station_name: 'Timboon West', capacity_mw: 7, region: 'VIC1' },
  'BLUFF1': { fuel_type: 'wind', station_name: 'The Bluff', capacity_mw: 53, region: 'SA1' },
  'BIALA1': { fuel_type: 'wind', station_name: 'Biala', capacity_mw: 111, region: 'NSW1' },
  'PAEPWF1': { fuel_type: 'wind', station_name: 'Port Augusta Energy Park', capacity_mw: 210, region: 'SA1' },
  'FERGUSON': { fuel_type: 'wind', station_name: 'Ferguson', capacity_mw: 12, region: 'VIC1' },
  'CROOKWELL': { fuel_type: 'wind', station_name: 'Crookwell', capacity_mw: 5, region: 'NSW1' },
  'GULRNWF1': { fuel_type: 'wind', station_name: 'Gullen Range', capacity_mw: 165, region: 'NSW1' },
  'KENEDYP': { fuel_type: 'wind', station_name: 'Kennedy Energy Park', capacity_mw: 43, region: 'QLD1' },
  'HAMPTON': { fuel_type: 'wind', station_name: 'Hampton', capacity_mw: 1, region: 'NSW1' },
  'MAROOWF1': { fuel_type: 'wind', station_name: 'Maroona', capacity_mw: 7, region: 'VIC1' },
  'MURRAWF1': { fuel_type: 'wind', station_name: 'Murra Warra', capacity_mw: 441, region: 'VIC1' },
  'BLAYNEY': { fuel_type: 'wind', station_name: 'Blayney', capacity_mw: 10, region: 'NSW1' },
  
  // Solar - Utility
  'ALDGASF1': { fuel_type: 'solar_utility', station_name: 'Aldoga', capacity_mw: 535, region: 'QLD1' },
  'AVLSF1': { fuel_type: 'solar_utility', station_name: 'Avonlie', capacity_mw: 254, region: 'NSW1' },
  'BANN1': { fuel_type: 'solar_utility', station_name: 'Bannerton', capacity_mw: 100, region: 'VIC1' },
  'BARCSF1': { fuel_type: 'solar_utility', station_name: 'Barcaldine', capacity_mw: 20, region: 'QLD1' },
  'BERYLSF1': { fuel_type: 'solar_utility', station_name: 'Beryl', capacity_mw: 98, region: 'NSW1' },
  'BLUEGSF1': { fuel_type: 'solar_utility', station_name: 'Blue Grass', capacity_mw: 183, region: 'QLD1' },
  'BNGSF1': { fuel_type: 'solar_utility', station_name: 'Bungala One', capacity_mw: 135, region: 'SA1' },
  'BNGSF2': { fuel_type: 'solar_utility', station_name: 'Bungala Two', capacity_mw: 135, region: 'SA1' },
  'BOLIVPS1': { fuel_type: 'solar_utility', station_name: 'Bolivar', capacity_mw: 8, region: 'SA1' },
  'BOMENSF1': { fuel_type: 'solar_utility', station_name: 'Bomen', capacity_mw: 121, region: 'NSW1' },
  'BROKENH1': { fuel_type: 'solar_utility', station_name: 'Broken Hill', capacity_mw: 53, region: 'NSW1' },
  'BULBES1': { fuel_type: 'solar_utility', station_name: 'Bulgana', capacity_mw: 0, region: 'VIC1' },
  'CHILDWF1': { fuel_type: 'solar_utility', station_name: 'Childers', capacity_mw: 64, region: 'QLD1' },
  'CHINCSF1': { fuel_type: 'solar_utility', station_name: 'Chinchilla', capacity_mw: 100, region: 'QLD1' },
  'CLARESF1': { fuel_type: 'solar_utility', station_name: 'Clare', capacity_mw: 110, region: 'QLD1' },
  'CLERMSF1': { fuel_type: 'solar_utility', station_name: 'Clermont', capacity_mw: 92, region: 'QLD1' },
  'COLESF1': { fuel_type: 'solar_utility', station_name: 'Coleambally', capacity_mw: 180, region: 'NSW1' },
  'COLVSF1': { fuel_type: 'solar_utility', station_name: 'Collinsville', capacity_mw: 42, region: 'QLD1' },
  'COLUMSF1': { fuel_type: 'solar_utility', station_name: 'Columboola', capacity_mw: 217, region: 'QLD1' },
  'COROWASF': { fuel_type: 'solar_utility', station_name: 'Corowa', capacity_mw: 36, region: 'NSW1' },
  'DARLSF1': { fuel_type: 'solar_utility', station_name: 'Darlington Point', capacity_mw: 324, region: 'NSW1' },
  'DARLDWNS': { fuel_type: 'solar_utility', station_name: 'Darling Downs', capacity_mw: 121, region: 'QLD1' },
  'DAYDSF1': { fuel_type: 'solar_utility', station_name: 'Daydream', capacity_mw: 167, region: 'QLD1' },
  'EDENSF1': { fuel_type: 'solar_utility', station_name: 'Edenvale', capacity_mw: 180, region: 'QLD1' },
  'EMERDSF1': { fuel_type: 'solar_utility', station_name: 'Emerald', capacity_mw: 88, region: 'QLD1' },
  'FINLYSF1': { fuel_type: 'solar_utility', station_name: 'Finley', capacity_mw: 162, region: 'NSW1' },
  'GANASF1': { fuel_type: 'solar_utility', station_name: 'Gannawarra', capacity_mw: 55, region: 'VIC1' },
  'GANGASF1': { fuel_type: 'solar_utility', station_name: 'Gangarri', capacity_mw: 162, region: 'QLD1' },
  'GLENWSF1': { fuel_type: 'solar_utility', station_name: 'Glenrowan', capacity_mw: 126, region: 'VIC1' },
  'GLROWSF1': { fuel_type: 'solar_utility', station_name: 'Glenrowan West', capacity_mw: 132, region: 'VIC1' },
  'GOONSF1': { fuel_type: 'solar_utility', station_name: 'Goonumbla', capacity_mw: 85, region: 'NSW1' },
  'GRIFSF1': { fuel_type: 'solar_utility', station_name: 'Griffith', capacity_mw: 27, region: 'NSW1' },
  'GUNNESF1': { fuel_type: 'solar_utility', station_name: 'Gunnedah', capacity_mw: 144, region: 'NSW1' },
  'HAMISF1': { fuel_type: 'solar_utility', station_name: 'Hamilton', capacity_mw: 58, region: 'QLD1' },
  'HAUGHSF1': { fuel_type: 'solar_utility', station_name: 'Haughton', capacity_mw: 132, region: 'QLD1' },
  'HAYMAN': { fuel_type: 'solar_utility', station_name: 'Hayman', capacity_mw: 58, region: 'QLD1' },
  'HILLSF1': { fuel_type: 'solar_utility', station_name: 'Hillston Sun', capacity_mw: 110, region: 'NSW1' },
  'HUGSF1': { fuel_type: 'solar_utility', station_name: 'Hughenden', capacity_mw: 21, region: 'QLD1' },
  'JEMALSF1': { fuel_type: 'solar_utility', station_name: 'Jemalong', capacity_mw: 55, region: 'NSW1' },
  'JUNESF1': { fuel_type: 'solar_utility', station_name: 'Junee', capacity_mw: 36, region: 'NSW1' },
  'KARADSF1': { fuel_type: 'solar_utility', station_name: 'Karadoc', capacity_mw: 104, region: 'VIC1' },
  'KERANSF1': { fuel_type: 'solar_utility', station_name: 'Kerang', capacity_mw: 37, region: 'VIC1' },
  'KIDSTSF1': { fuel_type: 'solar_utility', station_name: 'Kidston', capacity_mw: 50, region: 'QLD1' },
  'KIAMSF1': { fuel_type: 'solar_utility', station_name: 'Kiamal', capacity_mw: 239, region: 'VIC1' },
  'KINGSF1': { fuel_type: 'solar_utility', station_name: 'Kingaroy', capacity_mw: 47, region: 'QLD1' },
  'LIMSF1': { fuel_type: 'solar_utility', station_name: 'Limondale', capacity_mw: 275, region: 'NSW1' },
  'LIMSF2': { fuel_type: 'solar_utility', station_name: 'Limondale 2', capacity_mw: 38, region: 'NSW1' },
  'LILYVSF1': { fuel_type: 'solar_utility', station_name: 'Lilyvale', capacity_mw: 118, region: 'QLD1' },
  'LONGRSF1': { fuel_type: 'solar_utility', station_name: 'Longreach', capacity_mw: 17, region: 'QLD1' },
  'LRSF1': { fuel_type: 'solar_utility', station_name: 'Lucas Heights', capacity_mw: 0, region: 'NSW1' },
  'MANUMPS1': { fuel_type: 'solar_utility', station_name: 'Mannum', capacity_mw: 33, region: 'SA1' },
  'MANUSF2': { fuel_type: 'solar_utility', station_name: 'Mannum 2', capacity_mw: 37, region: 'SA1' },
  'MANISF1': { fuel_type: 'solar_utility', station_name: 'Manildra', capacity_mw: 50, region: 'NSW1' },
  'MARYSF1': { fuel_type: 'solar_utility', station_name: 'Maryrorough', capacity_mw: 33, region: 'QLD1' },
  'METZNSF1': { fuel_type: 'solar_utility', station_name: 'Metz N', capacity_mw: 135, region: 'NSW1' },
  'MIDDLSF1': { fuel_type: 'solar_utility', station_name: 'Middlemount', capacity_mw: 30, region: 'QLD1' },
  'MLSP1': { fuel_type: 'solar_utility', station_name: 'Molong', capacity_mw: 36, region: 'NSW1' },
  'MOKOSF1': { fuel_type: 'solar_utility', station_name: 'Mokoan', capacity_mw: 58, region: 'VIC1' },
  'MORASF1': { fuel_type: 'solar_utility', station_name: 'Moura', capacity_mw: 99, region: 'QLD1' },
  'MORESF1': { fuel_type: 'solar_utility', station_name: 'Moree', capacity_mw: 57, region: 'NSW1' },
  'MORGANWH': { fuel_type: 'solar_utility', station_name: 'Morganwhyalla Pipeline', capacity_mw: 22, region: 'SA1' },
  'MUGGASF1': { fuel_type: 'solar_utility', station_name: 'Mugga Lane', capacity_mw: 12, region: 'NSW1' },
  'NARROWSF': { fuel_type: 'solar_utility', station_name: 'Narromine', capacity_mw: 10, region: 'NSW1' },
  'NEVERTSF': { fuel_type: 'solar_utility', station_name: 'Nevertire', capacity_mw: 132, region: 'NSW1' },
  'NENGASF1': { fuel_type: 'solar_utility', station_name: 'New England', capacity_mw: 470, region: 'NSW1' },
  'NUMUSF1': { fuel_type: 'solar_utility', station_name: 'Numurkah', capacity_mw: 112, region: 'VIC1' },
  'NYNGASF1': { fuel_type: 'solar_utility', station_name: 'Nyngan', capacity_mw: 102, region: 'NSW1' },
  'OAKEY1SF': { fuel_type: 'solar_utility', station_name: 'Oakey', capacity_mw: 30, region: 'QLD1' },
  'OAKEY2SF': { fuel_type: 'solar_utility', station_name: 'Oakey 2', capacity_mw: 65, region: 'QLD1' },
  'PARKESF1': { fuel_type: 'solar_utility', station_name: 'Parkes', capacity_mw: 55, region: 'NSW1' },
  'ROSSRSF1': { fuel_type: 'solar_utility', station_name: 'Ross River', capacity_mw: 128, region: 'QLD1' },
  'ROYALLA1': { fuel_type: 'solar_utility', station_name: 'Royalla', capacity_mw: 20, region: 'NSW1' },
  'RUGBYSF1': { fuel_type: 'solar_utility', station_name: 'Rugby Run', capacity_mw: 83, region: 'QLD1' },
  'SEBASSF1': { fuel_type: 'solar_utility', station_name: 'Sebastopol', capacity_mw: 110, region: 'NSW1' },
  'STKSWSF1': { fuel_type: 'solar_utility', station_name: 'South Keswick', capacity_mw: 15, region: 'NSW1' },
  'STUBSF1': { fuel_type: 'solar_utility', station_name: 'Stubbo', capacity_mw: 503, region: 'NSW1' },
  'SUNMTSF1': { fuel_type: 'solar_utility', station_name: 'Sun Metals', capacity_mw: 143, region: 'QLD1' },
  'SUNRYSF1': { fuel_type: 'solar_utility', station_name: 'Sunraysia', capacity_mw: 228, region: 'NSW1' },
  'SUNSCSF1': { fuel_type: 'solar_utility', station_name: 'Sunshine Coast', capacity_mw: 15, region: 'QLD1' },
  'SUNTPSF1': { fuel_type: 'solar_utility', station_name: 'Suntop', capacity_mw: 175, region: 'NSW1' },
  'SUSARSF1': { fuel_type: 'solar_utility', station_name: 'Susan River', capacity_mw: 85, region: 'QLD1' },
  'TAILSF1': { fuel_type: 'solar_utility', station_name: 'Tailem Bend', capacity_mw: 108, region: 'SA1' },
  'TAILSF2': { fuel_type: 'solar_utility', station_name: 'Tailem Bend 2', capacity_mw: 105, region: 'SA1' },
  'WAGNSF1': { fuel_type: 'solar_utility', station_name: 'Wagga North', capacity_mw: 55, region: 'NSW1' },
  'WALLASF1': { fuel_type: 'solar_utility', station_name: 'Walla Walla', capacity_mw: 403, region: 'NSW1' },
  'WANDASF1': { fuel_type: 'solar_utility', station_name: 'Wandoan', capacity_mw: 159, region: 'QLD1' },
  'WANGASF1': { fuel_type: 'solar_utility', station_name: 'Wangaratta', capacity_mw: 26, region: 'VIC1' },
  'WARSF1': { fuel_type: 'solar_utility', station_name: 'Warwick', capacity_mw: 78, region: 'QLD1' },
  'WELLSF1': { fuel_type: 'solar_utility', station_name: 'Wellington', capacity_mw: 216, region: 'NSW1' },
  'WELLNSF1': { fuel_type: 'solar_utility', station_name: 'Wellington North', capacity_mw: 436, region: 'NSW1' },
  'WEMENSF1': { fuel_type: 'solar_utility', station_name: 'Wemen', capacity_mw: 97, region: 'VIC1' },
  'WESTWYSF': { fuel_type: 'solar_utility', station_name: 'West Wyalong', capacity_mw: 105, region: 'NSW1' },
  'WHITERFS': { fuel_type: 'solar_utility', station_name: 'White Rock Solar Farm', capacity_mw: 22, region: 'NSW1' },
  'WHITSF1': { fuel_type: 'solar_utility', station_name: 'Whitsunday', capacity_mw: 58, region: 'QLD1' },
  'WINTNSF1': { fuel_type: 'solar_utility', station_name: 'Winton', capacity_mw: 107, region: 'VIC1' },
  'WNSF1': { fuel_type: 'solar_utility', station_name: 'Woolooga', capacity_mw: 223, region: 'QLD1' },
  'WOLLSF1': { fuel_type: 'solar_utility', station_name: 'Wollar', capacity_mw: 324, region: 'NSW1' },
  'WUNGHSF1': { fuel_type: 'solar_utility', station_name: 'Wunghnu', capacity_mw: 94, region: 'VIC1' },
  'WYALSF1': { fuel_type: 'solar_utility', station_name: 'Wyalong', capacity_mw: 62, region: 'NSW1' },
  'YARRLSF1': { fuel_type: 'solar_utility', station_name: 'Yarranlea', capacity_mw: 121, region: 'QLD1' },
  'YATPSF1': { fuel_type: 'solar_utility', station_name: 'Yatpool', capacity_mw: 94, region: 'VIC1' },
  'YSWF1': { fuel_type: 'solar_utility', station_name: 'Yendon', capacity_mw: 0, region: 'VIC1' },
  'COHUSF1': { fuel_type: 'solar_utility', station_name: 'Cohuna', capacity_mw: 31, region: 'VIC1' },
  'GIRRSF1': { fuel_type: 'solar_utility', station_name: 'Girgarre', capacity_mw: 93, region: 'VIC1' },
  'GULRNSF1': { fuel_type: 'solar_utility', station_name: 'Gullen Range', capacity_mw: 10, region: 'NSW1' },
  'HAPPVSF1': { fuel_type: 'solar_utility', station_name: 'Happy Valley', capacity_mw: 11, region: 'SA1' },
  'KENEDYPS': { fuel_type: 'solar_utility', station_name: 'Kennedy Energy Park Solar', capacity_mw: 16, region: 'QLD1' },
  'MURRAYSF': { fuel_type: 'solar_utility', station_name: 'Murray Bridge-Onkaparinga', capacity_mw: 13, region: 'SA1' },
  'PAEPSSF1': { fuel_type: 'solar_utility', station_name: 'Port Augusta Energy Park', capacity_mw: 99, region: 'SA1' },
  'WDNSSF1': { fuel_type: 'solar_utility', station_name: 'Western Downs', capacity_mw: 501, region: 'QLD1' },
  'ADELSF1': { fuel_type: 'solar_utility', station_name: 'Adelaide Desalination', capacity_mw: 25, region: 'SA1' },
  'BAKESF1': { fuel_type: 'solar_utility', station_name: 'Baking Board', capacity_mw: 17, region: 'QLD1' },
  'CHRISB': { fuel_type: 'solar_utility', station_name: 'Christies Beach', capacity_mw: 4, region: 'SA1' },
  'CAPITAL': { fuel_type: 'solar_utility', station_name: 'Capital East', capacity_mw: 1, region: 'NSW1' },
  
  // Battery
  'BALB1': { fuel_type: 'battery', station_name: 'Ballarat', capacity_mw: 30, region: 'VIC1' },
  'BBATTERY1': { fuel_type: 'battery', station_name: 'Ballarat', capacity_mw: 30, region: 'VIC1' },
  'BESS1': { fuel_type: 'battery', station_name: 'Victorian Big Battery', capacity_mw: 300, region: 'VIC1' },
  'BWTR1': { fuel_type: 'battery', station_name: 'Broken Hill Battery', capacity_mw: 50, region: 'NSW1' },
  'CAPBES1': { fuel_type: 'battery', station_name: 'Capital', capacity_mw: 100, region: 'NSW1' },
  'CHINBES1': { fuel_type: 'battery', station_name: 'Chinchilla', capacity_mw: 100, region: 'QLD1' },
  'DALNTH01': { fuel_type: 'battery', station_name: 'Dalrymple North', capacity_mw: 30, region: 'SA1' },
  'DARLNBES': { fuel_type: 'battery', station_name: 'Darlington Point', capacity_mw: 25, region: 'NSW1' },
  'GANBES1': { fuel_type: 'battery', station_name: 'Gannawarra', capacity_mw: 25, region: 'VIC1' },
  'GREENBES': { fuel_type: 'battery', station_name: 'Greenbank', capacity_mw: 200, region: 'QLD1' },
  'HAPPVBES': { fuel_type: 'battery', station_name: 'Happy Valley', capacity_mw: 12, region: 'SA1' },
  'HAZBATT1': { fuel_type: 'battery', station_name: 'Hazelwood BESS', capacity_mw: 150, region: 'VIC1' },
  'HPRL1': { fuel_type: 'battery', station_name: 'Hornsdale Power Reserve', capacity_mw: 150, region: 'SA1' },
  'KENEDYB': { fuel_type: 'battery', station_name: 'Kennedy Energy Park', capacity_mw: 60, region: 'QLD1' },
  'KOORBAT1': { fuel_type: 'battery', station_name: 'Koorangie', capacity_mw: 185, region: 'VIC1' },
  'LKBONNYB': { fuel_type: 'battery', station_name: 'Lake Bonney Battery', capacity_mw: 25, region: 'SA1' },
  'LATRBATT': { fuel_type: 'battery', station_name: 'Latrobe Valley', capacity_mw: 100, region: 'VIC1' },
  'MANUBAT1': { fuel_type: 'battery', station_name: 'Mannum', capacity_mw: 100, region: 'SA1' },
  'MELABATT': { fuel_type: 'battery', station_name: 'Melbourne A1', capacity_mw: 200, region: 'VIC1' },
  'PHILBES1': { fuel_type: 'battery', station_name: 'Phillip Island', capacity_mw: 5, region: 'VIC1' },
  'QUEBATT1': { fuel_type: 'battery', station_name: 'Queanbeyan', capacity_mw: 10, region: 'NSW1' },
  'RANGBAT1': { fuel_type: 'battery', station_name: 'Rangebank', capacity_mw: 200, region: 'VIC1' },
  'RIVER1': { fuel_type: 'battery', station_name: 'Riverina 1', capacity_mw: 60, region: 'NSW1' },
  'RIVER2': { fuel_type: 'battery', station_name: 'Riverina 2', capacity_mw: 65, region: 'NSW1' },
  'TAILBES2': { fuel_type: 'battery', station_name: 'Tailem Bend 2', capacity_mw: 128, region: 'SA1' },
  'TARONGBS': { fuel_type: 'battery', station_name: 'Tarong', capacity_mw: 300, region: 'QLD1' },
  'TEMPBAT1': { fuel_type: 'battery', station_name: 'Templers', capacity_mw: 111, region: 'SA1' },
  'TORRBES1': { fuel_type: 'battery', station_name: 'Torrens Island', capacity_mw: 250, region: 'SA1' },
  'VICBATT1': { fuel_type: 'battery', station_name: 'Victorian Big Battery', capacity_mw: 300, region: 'VIC1' },
  'WALLBATT': { fuel_type: 'battery', station_name: 'Wallgrove', capacity_mw: 50, region: 'NSW1' },
  'WANDBAT1': { fuel_type: 'battery', station_name: 'Wandoan South', capacity_mw: 100, region: 'QLD1' },
  'WARATSB1': { fuel_type: 'battery', station_name: 'Waratah Super Battery', capacity_mw: 850, region: 'NSW1' },
  'WDNSBAT1': { fuel_type: 'battery', station_name: 'Western Downs', capacity_mw: 255, region: 'QLD1' },
  'ADELDES': { fuel_type: 'battery', station_name: 'Adelaide Desalination', capacity_mw: 25, region: 'SA1' },
  'BLYTHBAT': { fuel_type: 'battery', station_name: 'Blyth', capacity_mw: 200, region: 'SA1' },
  'BOULBAT1': { fuel_type: 'battery', station_name: 'Bouldercombe', capacity_mw: 50, region: 'QLD1' },
  'BULGABAT': { fuel_type: 'battery', station_name: 'Bulgana Green Power Hub', capacity_mw: 224, region: 'VIC1' },
  'ERATBAT1': { fuel_type: 'battery', station_name: 'Eraring', capacity_mw: 460, region: 'NSW1' },
  
  // Bioenergy
  'CONDONG1': { fuel_type: 'bioenergy_biomass', station_name: 'Condong', capacity_mw: 30, region: 'NSW1' },
  'BROADW1': { fuel_type: 'bioenergy_biomass', station_name: 'Broadwater', capacity_mw: 38, region: 'NSW1' },
  'RPCG': { fuel_type: 'bioenergy_biomass', station_name: 'Rocky Point Cogen', capacity_mw: 30, region: 'QLD1' },
  'PIONEER': { fuel_type: 'bioenergy_biomass', station_name: 'Pioneer Sugar Mill', capacity_mw: 68, region: 'QLD1' },
  'INVIC': { fuel_type: 'bioenergy_biomass', station_name: 'Invicta Sugar Mill', capacity_mw: 50, region: 'QLD1' },
  'ISIS': { fuel_type: 'bioenergy_biomass', station_name: 'Isis Central Sugar Mill', capacity_mw: 25, region: 'QLD1' },
  'MACKNTSH': { fuel_type: 'bioenergy_biomass', station_name: 'Mackay', capacity_mw: 38, region: 'QLD1' },
  'TABLSF1': { fuel_type: 'bioenergy_biomass', station_name: 'Tableland Mill', capacity_mw: 24, region: 'QLD1' },
  'VICTSF1': { fuel_type: 'bioenergy_biomass', station_name: 'Victoria Mill', capacity_mw: 24, region: 'QLD1' },
  'RACECSF1': { fuel_type: 'bioenergy_biomass', station_name: 'Racecourse Mill', capacity_mw: 49, region: 'QLD1' },
  'TULLYSM1': { fuel_type: 'bioenergy_biomass', station_name: 'Tully Sugar Mill', capacity_mw: 28, region: 'QLD1' },
  
  // Gas - Waste Coal Mine
  'APPIN1': { fuel_type: 'gas_wcm', station_name: 'Appin', capacity_mw: 56, region: 'NSW1' },
  'GLENNIES': { fuel_type: 'gas_wcm', station_name: 'Glennies Creek', capacity_mw: 13, region: 'NSW1' },
  'GROSV1': { fuel_type: 'gas_wcm', station_name: 'Grosvenor 1', capacity_mw: 21, region: 'QLD1' },
  'GROSV2': { fuel_type: 'gas_wcm', station_name: 'Grosvenor 2', capacity_mw: 15, region: 'QLD1' },
  'MORABNTH': { fuel_type: 'gas_wcm', station_name: 'Moranbah North', capacity_mw: 63, region: 'QLD1' },
  'OAKCR1': { fuel_type: 'gas_wcm', station_name: 'Oaky Creek', capacity_mw: 15, region: 'QLD1' },
  'OAKCR2': { fuel_type: 'gas_wcm', station_name: 'Oaky Creek 2', capacity_mw: 15, region: 'QLD1' },
  'TAHMOOR': { fuel_type: 'gas_wcm', station_name: 'Tahmoor', capacity_mw: 7, region: 'NSW1' },
  'TOWER': { fuel_type: 'gas_wcm', station_name: 'Tower', capacity_mw: 41, region: 'NSW1' },
  'GERMCRKM': { fuel_type: 'gas_wcm', station_name: 'German Creek Mine', capacity_mw: 45, region: 'QLD1' },
  
  // Gas - Reciprocating
  'BARKIPS1': { fuel_type: 'gas_recip', station_name: 'Barker Inlet', capacity_mw: 211, region: 'SA1' },
  'MORANBAH': { fuel_type: 'gas_recip', station_name: 'Moranbah', capacity_mw: 13, region: 'QLD1' },
  'OAKCR': { fuel_type: 'gas_recip', station_name: 'Oaky Creek', capacity_mw: 20, region: 'QLD1' },
  'WILGAPK1': { fuel_type: 'gas_recip', station_name: 'Wilga Park', capacity_mw: 10, region: 'NSW1' },
  'WILGAPK2': { fuel_type: 'gas_recip', station_name: 'Wilga Park B', capacity_mw: 12, region: 'NSW1' },
  'TRARALGN': { fuel_type: 'gas_recip', station_name: 'Traralgon Network Support', capacity_mw: 10, region: 'VIC1' },
  'BALLHOSP': { fuel_type: 'gas_recip', station_name: 'Ballarat Hospital', capacity_mw: 1, region: 'VIC1' },
  
  // Distillate/Diesel
  'ANGAST1': { fuel_type: 'distillate', station_name: 'Angaston', capacity_mw: 50, region: 'SA1' },
  'BDL01': { fuel_type: 'distillate', station_name: 'Broken Hill', capacity_mw: 25, region: 'NSW1' },
  'BDL02': { fuel_type: 'distillate', station_name: 'Broken Hill', capacity_mw: 25, region: 'NSW1' },
  'ERGT01': { fuel_type: 'distillate', station_name: 'Eraring', capacity_mw: 21, region: 'NSW1' },
  'ERGT02': { fuel_type: 'distillate', station_name: 'Eraring', capacity_mw: 21, region: 'NSW1' },
  'HUNTER': { fuel_type: 'distillate', station_name: 'Hunter Economic Zone', capacity_mw: 28, region: 'NSW1' },
  'LONSDALE': { fuel_type: 'distillate', station_name: 'Lonsdale', capacity_mw: 20, region: 'SA1' },
  'MACKAY1': { fuel_type: 'distillate', station_name: 'Mackay', capacity_mw: 34, region: 'QLD1' },
  'MTSTUAR1': { fuel_type: 'distillate', station_name: 'Mt Stuart', capacity_mw: 419, region: 'QLD1' },
  'PORTLINC': { fuel_type: 'distillate', station_name: 'Port Lincoln', capacity_mw: 74, region: 'SA1' },
  'PORTSTAN': { fuel_type: 'distillate', station_name: 'Port Stanvac', capacity_mw: 58, region: 'SA1' },
  'SNUG1': { fuel_type: 'distillate', station_name: 'Snuggery', capacity_mw: 84, region: 'SA1' },
  'TATARIA': { fuel_type: 'distillate', station_name: 'Tataria', capacity_mw: 1, region: 'SA1' },
  'WESTCLUB': { fuel_type: 'distillate', station_name: 'Western Suburbs League Club', capacity_mw: 1, region: 'NSW1' },
  'WESTILLAW': { fuel_type: 'distillate', station_name: 'West Illawarra Leagues Club', capacity_mw: 1, region: 'NSW1' },
  'STGEORGE': { fuel_type: 'distillate', station_name: 'St George Leagues Club', capacity_mw: 1, region: 'NSW1' },
  
  // Additional units with pattern-based naming
  'CG1': { fuel_type: 'black_coal', station_name: 'Callide', capacity_mw: 120, region: 'QLD1' },
  'CG2': { fuel_type: 'black_coal', station_name: 'Callide', capacity_mw: 120, region: 'QLD1' },
  'CG3': { fuel_type: 'black_coal', station_name: 'Callide', capacity_mw: 120, region: 'QLD1' },
  'CG4': { fuel_type: 'black_coal', station_name: 'Callide', capacity_mw: 120, region: 'QLD1' },
  'LD01': { fuel_type: 'black_coal', station_name: 'Liddell', capacity_mw: 500, region: 'NSW1' },
  'LD02': { fuel_type: 'black_coal', station_name: 'Liddell', capacity_mw: 500, region: 'NSW1' },
  'LD03': { fuel_type: 'black_coal', station_name: 'Liddell', capacity_mw: 500, region: 'NSW1' },
  'LD04': { fuel_type: 'black_coal', station_name: 'Liddell', capacity_mw: 500, region: 'NSW1' },
  'GB01': { fuel_type: 'gas_ocgt', station_name: 'Goldfields', capacity_mw: 40, region: 'WA1' },
  'LI_WY_CA': { fuel_type: 'hydro', station_name: 'Lake Lyell', capacity_mw: 50, region: 'NSW1' },
  'LEM_WIL': { fuel_type: 'hydro', station_name: 'Lemonthyme Wilmot', capacity_mw: 82, region: 'TAS1' },
  'SHGEN': { fuel_type: 'hydro', station_name: 'Shoalhaven', capacity_mw: 240, region: 'NSW1' },
  'TIB1': { fuel_type: 'hydro', station_name: 'Tibooburra', capacity_mw: 0, region: 'NSW1' },
  'MBAHNTH': { fuel_type: 'bioenergy_biomass', station_name: 'Maryborough', capacity_mw: 10, region: 'QLD1' },
  'PALOONA': { fuel_type: 'hydro', station_name: 'Paloona', capacity_mw: 28, region: 'TAS1' },
  'HUMENSW': { fuel_type: 'hydro', station_name: 'Hume', capacity_mw: 29, region: 'NSW1' },
  'ADPBA1': { fuel_type: 'battery', station_name: 'Adelaide', capacity_mw: 10, region: 'SA1' },
  'ADPPV1': { fuel_type: 'solar_utility', station_name: 'Adelaide', capacity_mw: 10, region: 'SA1' },
  'AGLHAL': { fuel_type: 'gas_ocgt', station_name: 'Hallett', capacity_mw: 217, region: 'SA1' },
  'AGLSOM': { fuel_type: 'gas_ocgt', station_name: 'Somerton', capacity_mw: 170, region: 'VIC1' },
  'BHB1': { fuel_type: 'bioenergy_biogas', station_name: 'Brisbane', capacity_mw: 1, region: 'QLD1' },
  'BLYTHB1': { fuel_type: 'battery', station_name: 'Blyth', capacity_mw: 200, region: 'SA1' },
  'BOWWBA1': { fuel_type: 'battery', station_name: 'Bowmans Creek', capacity_mw: 0, region: 'NSW1' },
  'BOWWPV1': { fuel_type: 'solar_utility', station_name: 'Bowmans Creek', capacity_mw: 0, region: 'NSW1' },
  'CBWWBA1': { fuel_type: 'battery', station_name: 'Capital', capacity_mw: 100, region: 'NSW1' },
  'HVWWBA1': { fuel_type: 'battery', station_name: 'Hunter Valley', capacity_mw: 0, region: 'NSW1' },
  'KEPBG1': { fuel_type: 'bioenergy_biogas', station_name: 'Kepco', capacity_mw: 1, region: 'NSW1' },
  'MCKAY1': { fuel_type: 'hydro', station_name: 'Mackay', capacity_mw: 38, region: 'QLD1' },
  'PAREPW1': { fuel_type: 'wind', station_name: 'Paling Yards', capacity_mw: 0, region: 'NSW1' },
  'WALGRV1': { fuel_type: 'wind', station_name: 'Wallerawang', capacity_mw: 0, region: 'NSW1' },
};

// Helper function to get fuel type from DUID
export function getFuelType(duid: string): string {
  const upperDuid = duid.toUpperCase();
  const info = DUID_FUEL_MAP[upperDuid];
  return info ? info.fuel_type : 'unknown';
}

// Helper function to get full generator info
export function getGeneratorInfo(duid: string): GeneratorInfo | null {
  const upperDuid = duid.toUpperCase();
  return DUID_FUEL_MAP[upperDuid] || null;
}

// Aggregate fuel types to broader categories
export function aggregateFuelTypes(fuelType: string): string {
  const coalTypes = ['black_coal', 'brown_coal'];
  const gasTypes = ['gas_ccgt', 'gas_ocgt', 'gas_steam', 'gas_recip', 'gas_wcm'];
  const renewableTypes = ['wind', 'solar_utility', 'solar_rooftop', 'hydro'];
  const bioenergyTypes = ['bioenergy_biomass', 'bioenergy_biogas'];
  
  if (coalTypes.includes(fuelType)) return 'coal';
  if (gasTypes.includes(fuelType)) return 'gas';
  if (renewableTypes.includes(fuelType)) return fuelType;
  if (bioenergyTypes.includes(fuelType)) return 'bioenergy';
  if (fuelType === 'battery') return 'battery';
  if (fuelType === 'distillate') return 'distillate';
  
  return 'other';
}